#!/bin/bash
#SBATCH --qos regular
#SBATCH --constraint haswell
#SBATCH --nodes 2
#SBATCH --cpus-per-task 32
#SBATCH --time 01:00:00
#SBATCH --license cscratch1
#SBATCH --mail-type ALL
#SBATCH --mail-user yx59@duke.edu
#SBATCH --output  /global/cscratch1/sd/yx59/slurm/%x-%j
#SBATCH --error   /global/cscratch1/sd/yx59/slurm/%x-%j
#SBATCH --workdir /global/cscratch1/sd/yx59/pPb2/inputfiles


# export environment variables
export CONDA_PREFIX=/global/common/software/m2730/hic_yx
export PATH=$CONDA_PREFIX/bin:$PATH
export XDG_DATA_HOME=$CSCRATCH/share
export THREADS=32

# design input files
design=$CSCRATCH/pPb2/inputfiles
inputfiles=$(find $design -type f)
ntasks=200

# unique job identifier
job=$NERSC_HOST-$SLURM_JOB_ID

# list of input files and grid sizes
function design_point_gridsize {
  for file in $inputfiles; do
    width=$(grep parton-width $file | awk '{print $NF}')
    echo $width $file
  done
}

# sort input files by grid size (proxy for run time)
inputfiles=$(design_point_gridsize | sort | awk '{print $NF}')

# create taskfarmer working directory
workdir=$CSCRATCH/taskfarmer/$SLURM_JOB_NAME-$NERSC_HOST-$SLURM_JOB_ID
mkdir -p $workdir
cd $workdir

# create taskfarmer tasks
for file in $inputfiles; do
  for task in $(seq -f "%05g" $ntasks); do
    echo run-events \
      --nevents 25 \
      --grid-scale 0.2 \
      --logfile $CSCRATCH/logs/$job/$file/$task.log \
      @$CSCRATCH/pPb2/inputfiles/$file \
      $CSCRATCH/events/pPb2/$file/$job/$task.dat >> tasks
  done
done

# run tasks
module load taskfarmer
runcommands.sh tasks
